name: Bob The Builder

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Fetching Materials
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Construction
      env:
        GH_TOKEN:       ${{ secrets.token }}
        GH_REPO:        ${{ github.repository }}
        STORE_PASS:     ${{ secrets.STORE_PASS }}
        KEY_ALIAS:      ${{ secrets.KEY_ALIAS }}
        KEY_PASS:       ${{ secrets.KEY_PASS }}
      run: |
              sudo /usr/local/lib/android/tools/bin/sdkmanager --install "ndk;20.0.5594570" --sdk_root=${ANDROID_SDK_ROOT} > /dev/null
              ./gradlew assembleRelease
              bash pushbuild.sh "arm64-v8a"
              sed -i.bak s/armeabi-v7a/arm64-v8a/ app/build.gradle
              ./gradlew assembleRelease
              bash pushbuild.sh "armeabi-v7a"
